#服务器端口
server:
  port: 8180

#数据源配置
spring:

  datasource:
    url: jdbc:mysql://106.53.148.248:13306/edu_sys?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: cx
    password: 263niubi.

wechat:
  appid: wxb31375890217af9b
  secret: 09587e34ac1404665b12df3fcdb2c427